#!/bin/bash
if [ ! -f "install_dependencies" ]; then
    echo "Wrong working dir! Execute when in root of Project!"
    exit 1
fi

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root for the \"make install\" sections"
    exit 1
fi
if [ ! -d "lib" ]; then
    mkdir lib
fi
cd lib

#FFTW3.3.10
if [ ! -d "fftw3" ]; then
    #download fftw3 from http://www.fftw.org/
    echo "downloading fftw3 now..."
    mkdir fftw3
    cd fftw3
    wget http://www.fftw.org/fftw-3.3.10.tar.gz
    tar -xf fftw-3.3.10.tar.gz --strip 1
    rm fftw-3.3.10.tar.gz
    cd ..
fi
if [ ! -f "/usr/local/include/fftw3.h" ]; then
    echo "installing fftw3 now..."
    cd fftw3
    ./configure
    make
    sudo make install
    cd ..
fi

#WS281x
if [ ! -d "rpi_ws281x" ]; then 
    #get specific commit from archife of https://github.com/jgarff/rpi_ws281x
    echo "downloading ws281x library now..."
    wget https://github.com/jgarff/rpi_ws281x/archive/ee7522e3b053950af33bc7e4364742cd3aeaf594.zip
    unzip ee7522e3b053950af33bc7e4364742cd3aeaf594.zip
    mv rpi_ws281x-ee7522e3b053950af33bc7e4364742cd3aeaf594/ rpi_ws281x
    rm ee7522e3b053950af33bc7e4364742cd3aeaf594.zip
fi
if [ ! -d "/usr/local/include/ws2811" ]; then
    #make and make install
    echo "installing ws2811 now..."
    cd rpi_ws281x
    cmake CMakeLists.txt
    make
    sudo make install
    cd ..
fi

#Portaudio
if [ ! -d "portaudio" ]; then
    #download stable release 19.7 from portaudio (http://files.portaudio.com/)
    echo "downloading portaudio now..."
    wget http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz
    tar -xf pa_stable_v190700_20210406.tgz
    rm pa_stable_v190700_20210406.tgz
fi
if [ ! -f "/usr/local/include/portaudio.h" ]; then
    echo "installing portaudio now..."
    cd portaudio
    ./configure
    make
    sudo make install
    cd ..
fi

#WiringPi
if [ ! -d "WiringPi" ]; then
    #download specific Commit directly from git
    wget "https://github.com/WiringPi/WiringPi/archive/5de0d8f5739ccc00ab761639a7e8d3d1696a480a.zip"
    unzip 5de0d8f5739ccc00ab761639a7e8d3d1696a480a.zip
    mv WiringPi-5de0d8f5739ccc00ab761639a7e8d3d1696a480a/ WiringPi/
fi
if [ ! -f "/usr/local/include/wiringPi.h" ]; then
    #use automatic script to install wiringPi
    cd WiringPi
    ./build
    cd ..
fi
cd ..